#!/bin/sh

error() {
    echo "$@"
    exit 1
}

open() {
    URLS="$@"
    if "${MXC}" -a "${APPNAME}" -p "${PROFILE}" 'ping()' ; then
        for url in ${URLS} ; do
            "${MXC}" -a "${APPNAME}" -p "${PROFILE}" "openURL(${url})"
        done
    else
        "${APPNAME}" -new-instance -P "${PROFILE}" "$@"
    fi
}

checkpath() {
    local testpath testfile
    testpath="${1}"

    testfile="$(echo ${testpath} | tail -n1)"
    if [ -x "${testfile}" ]
    then
        echo "${testfile}"
    else
        echo ""
    fi
}


DEFAULT_PROFILE="default"

if command -v iceweasel ; then
    APPNAME="iceweasel"
else
    APPNAME="firefox"
fi

MXC="$(command -v mozilla-xremote-client)"

# Debian
if [ -z "${MXC}" ] ; then
    MXC=$(checkpath "/usr/lib/xulrunner-[0-9]*/mozilla-xremote-client")
fi

# Fedora
if [ -z "${MXC}" ] ; then
    MXC=$(checkpath "/usr/lib*/firefox/mozilla-xremote-client")
fi

if [ -z "${MXC}" -o ! -x "${MXC}" ] ; then
    error mozilla-xremote-client not found. exiting.
fi

case "$1" in
    http://*|https://*|file://*)
        PROFILE="${DEFAULT_PROFILE}"
        ;;
    *)
        PROFILE="$1"
        shift
        ;;
esac

open "$@"
